name: Generate Chapters
on:
  workflow_dispatch:

jobs:
  generate-chapters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Chapter Files
        run: |
          mkdir -p chapters
          for i in {3..100}; do
          cat << "EOF" > chapters/chapter$i.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="0">
    <title>Chapter $i | pkltheshaboy</title>
    <link rel="stylesheet" href="../styles/style.css">
</head>
<body>
    <div class="main-container">
        <header>
            <img src="../assets/images/logo.png" alt="Logo" class="logo">
        </header>
        <div class="chapter-title">
            chapter $i
        </div>
        <main class="chapter-content">
            <!-- Content sections -->
        </main>
    </div>
    <script src="../scripts/script.js"></script>
</body>
</html>
EOF
          done

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add chapters/
          git diff --quiet || (git commit -m "Auto-generated chapters 3-100" && git push)
