name: Generate Chapters
on:
  workflow_dispatch:

jobs:
  generate-chapters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Chapters
        run: |
          mkdir -p chapters
          for i in {3..100}; do
            echo "<html><body>Chapter $i</body></html>" > chapters/chapter$i.html
          done

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add chapters/
          git diff --quiet || (git commit -m "Add generated chapters" && git push)
