name: Generate Chapters
on:
  workflow_dispatch:

jobs:
  generate-chapters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Generate Chapter Files
      run: |
        mkdir -p chapters
        for i in {1..100}; do
        cat << "EOF" > chapters/chapter$i.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chapter $i | pkltheshaboy</title>
    <link rel="stylesheet" href="../styles/style.css">
</head>
<body>
    <div class="main-container">
        <header>
            <img src="../assets/images/logo.png" alt="Logo" class="logo">
        </header>

        <main class="chapter-content">
            <div class="chapter-cover">
                <img src="../assets/covers/chapter$i-cover.jpg" alt="Chapter $i Cover">
            </div>

            <div class="music-player">
                <iframe src="https://open.spotify.com/embed/track/TRACK_ID" 
                        width="100%" 
                        height="380" 
                        frameborder="0" 
                        allowtransparency="true" 
                        allow="encrypted-media">
                </iframe>
            </div>

            <div class="quote-section">
                <em>"CHAPTER_QUOTE"</em>
            </div>

            <div class="chapter-nav">
                <button class="nav-button" onclick="navigateChapter(-1)">previous</button>
                <button class="nav-button" onclick="navigateChapter(1)">next</button>
            </div>
        </main>
    </div>
    <script src="../scripts/script.js"></script>
</body>
</html>
EOF
        done

    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add chapters/
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generated 100 chapters"
        git push
