name: Generate Chapters
on:
  workflow_dispatch:
  
jobs:
  generate-chapters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Chapter Files
        run: |
          mkdir -p chapters
          for i in {1..100}; do
            cat << EOF > chapters/chapter$i.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chapter $i | pkltheshaboy</title>
    <link rel="stylesheet" href="../styles/style.css">
</head>
<body>
    <!-- Your chapter template here -->
    <div class="chapter-nav">
        <button onclick="navigateChapter(-1)">previous</button>
        <button onclick="navigateChapter(1)">next</button>
    </div>
</body>
</html>
EOF
          done
          
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add chapters/
          git commit -m "Auto-generated 100 chapters"
          git push
